## Configuration

You can configure the following parameters in your application.yml.

.Plugin Configuration Options
[cols="3,1,1,10"]
|===
| Key | Default | Optional | Description

| grails.plugin.springsecurity.oauth2.active
| true
| true
| Whether the plugin is active or not

| grails.plugin.springsecurity.oauth2.registration.askToLinkOrCreateAccountUri
| /oauth2/ask
| true
| The URI is called to ask the user to either create a new account or link an existing

| grails.plugin.springsecurity.oauth2.registration.roleNames
| ['ROLE_USER']
| true
| A list of role names that should be automatically granted to OAuth User. There roles will be created if they do not exists
|===

Here is an example configuration file:

.application.yml
[source,yaml]
----
grails:
  plugin:
    springsecurity:
      oauth2:
        active: true
        registration:
          askToLinkOrCreateAccountUri: /oauth2/ask
          roleNames: ['ROLE_USER']
----

### Initializing

Once you have a User domain class, initialize this plugin by using the init script
[source,bash]
----
grails init-oauth2 <domain-class-package> <user-class-name> <oauthid-class-name>
----

The above command will create the domain class with the provided name and package. For example, the command `grails init-oauth2 com.yourapp User OAuthID` will create a domain class `OAuthID.groovy`.

Finally, you also need to add the following domain class relationship mapping to User.groovy domain class:

.grails-app/domain/com/yourapp/User.groovy
[source,groovy]
----
package com.yourapp

class User {

    // ...

    static hasMany = [oAuthIDs: OAuthID]

}
----
